apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: unco
  namespace: production
spec:
  maxReplicas: 25
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unco
  targetCPUUtilizationPercentage: 100