steps:
- id: Build-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/production/my-static-web-app:$latest', '.']
  timeout: 900s

- id: Push-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['Push', 'asia.gcr.io/$PROJECT_ID/production/my-static-web-app:$latest']
  timeout: 900s

- id: envSubst-for-deployment.yml
  name: 'gcr.io/$PROJECT_ID/envsubst'
  env:
    - 'latest=$latest'
    - 'PROJECT_ID=$PROJECT_ID'
  args: ['deployment.yaml']

- id: Deploy-to-GKE
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --cluster=unco-production
  - --location=asia-southeast2-a
  timeout: 900s

  # Global Timeout .....