steps:
- id: Build-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/unco-412009/production/unco:$SHORT_SHA', '.']
  timeout: 900s

- id: Push-docker
  name: 'gcr.io/cloud-builders/docker'
  args: ['Push', 'asia.gcr.io/unco-412009/production/unco:$SHORT_SHA']
  timeout: 900s

- id: envSubst-for-deployment.yml
  name: 'gcr.io/unco-412009/envsubst'
  env:
    - 'SHORT_SHA=$SHORT_SHA'
    - 'unco-412009=unco-412009'
  args: ['deployment.yaml']

- id: Deploy-to-GKE
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --cluster=unco-production
  - --location=asia-southeast2-a
  timeout: 900s

  # Global Timeout .....